//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Book()
        {
            this.Tbl_Reservation = new HashSet<Tbl_Reservation>();
        }
    
        public int Id_Book { get; set; }
        public string Book_Name { get; set; }
        public Nullable<int> FK_Status_Id { get; set; }
        public Nullable<int> FK_Writer_Id { get; set; }
        public Nullable<int> FK_Category_Id { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Status Tbl_Status { get; set; }
        public virtual Tbl_Writer Tbl_Writer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reservation> Tbl_Reservation { get; set; }
    }
}
