//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Penalty = new HashSet<Tbl_Penalty>();
            this.Tbl_Reservation = new HashSet<Tbl_Reservation>();
        }
    
        public int Id_User { get; set; }
        public Nullable<int> FK_UserTypeID { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
        public string User_Password { get; set; }
        public string User_UserNick { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Penalty> Tbl_Penalty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reservation> Tbl_Reservation { get; set; }
        public virtual Tbl_UserType Tbl_UserType { get; set; }
    }
}
